### PR TITLE
Rewrite package interface

### PR DESCRIPTION
**Pull request by barrywardell**
This is a rewrite of the interface part of the package, to simplify things and make the option handling more robust. It removes support for having multiple homogeneous solutions inside a single ReggeWheelerRadialFunction as it over-complicated things with little gain.

### CODE REVIEW

**Comment by barrywardell** [comment]
The attached notebook gives examples of how to use the new interface.
[ReggeWheelerExamples.nb.zip](https://github.com/BlackHolePerturbationToolkit/ReggeWheeler/files/4301145/ReggeWheelerExamples.nb.zip)

**Comment by nielsw2** [comment]
This is all looking very nice. I am not completely sure about the 'All' option for the numerical integration. I wonder if instead the ReggeWheelerRadialFunction should store the domain which for MST is {2, Infinity} and for the numerical case is whatever domain was set. The function would then only evaluate for radial values within the domain.

**Comment by nielsw2** [comment]
I checked all the changes and they work well for me. Just one remaining question: if we pass a list of values to the ReggeWheelerRadialFunction, should we check that each of them is within the domain? Or maybe just check that the min and max values in the list are within the domain?

**Comment by nielsw2** [comment]
Everything looks good so I will merge this.

**Pull request merged**
